### PR TITLE
Feature: New Sidebar Links & Pages

### LINKED ISSUE #148: Add sidebar links
I'd like to add links to the lefthand sidebar. Something kind of like this but less ugly:

image

I'd like the links to be:

* Blog -> points to blog index
* About Me -> points to a page where I can add a bio and a photo. For filler, we can start with "Michael Lynch is a blogger on the Internet."
* Projects -> Points to a page where I can include links to posts or external URLs and add blurbs. For first version, we can just start with links to [GreenPiThumb](https://mtlynch.io/greenpithumb/) and [ProsperBot](https://mtlynch.io/prosperbot/) with no blurbs.

### PR DESCRIPTION
**Pull request by shredtechular**
This PR adds a new sidebar navigation to the website that is very easy to update and maintain and breaks down well responsively.  As we are adding new navigational links, this PR also stubs out the new pages for "About" and "Projects".

## How the current implementation looks:
First, I wanted to display a few screenshots to illustrate how the new sidebar and associated pages look when built using the feature branch from this PR.

### 1. Blog index page with new sidebar links and active item bolded (desktop version).
Also notice, no more masthead on desktop as that is what we will use for responsive breakdown of the sidebar menu.
<kbd>
screen shot 2017-09-25 at 10 28 39 pm
</kbd>

### 2. Blog index page (ipad size version).
<kbd>
screen shot 2017-09-25 at 10 28 58 pm
</kbd>

### Closed menu
img_0529

    <br><br>

### Open menu

img_0530

### 3. About page (w/no email subscription)
<kbd>
screen shot 2017-09-25 at 10 39 07 pm
</kbd>

### 4. Projects page (w/no email subscription)
<kbd>
screen shot 2017-09-25 at 10 39 14 pm
</kbd>

## Additional details on solution
- [X] The parent theme provides an out-of-the-box capability for sidebar links & a masthead menu.  Based on their documentation, this was done by associating the main menu items in `_data/navigation.yml` with the `sidebar:` frontmatter item in the config for the default setups for posts & pages.  So, that provides us the capability to have a sidebar on desktop versions and a mobile top nav on responsive versions of the site.
- [X] The parent theme uses a "priority plus" [methodology](https://mmistakes.github.io/minimal-mistakes/docs/navigation/) for hiding/showing necessary top nav links based on browser width.  If you don't like how it shows hides nav items based on width, we could customize the parent theme to remove the "priority plus" navigation.
- [X] In order to have the sidebar breakdown responsively into a mobile hamburger type menu, we did have to customize the `_includes/masthead.html` from the parent.  Just wanted to point this out for future theme upgrades.
- [X] Also addressed the sidebar font size, changing "About Me" to just "About", and adding a capability to hide the email signup form on individual pages by adding a `hide_signup: true` frontmatter key to pages that the signup form should be hidden.

## Testing
This has now been tested across the following browsers/devices:
- [X] Mac Chrome, FF, Safari
- [X] Iphone 5 Chrome, Safari
- [X] Win10 Edge, IE 11, Chrome, FF
- [X] General responsiveness

This PR fixes #148.

### CODE REVIEW

**Comment by mtlynch** [comment]
This looks good!

>Are you okay with the styling of the links for the sidebar on the main desktop view?

I like it, but the text feels a little too small. Could we make it a bit larger? I feel like it has to either be as large as the "New York, NY" text or larger.

>I'm not sure I like the way the links breakdown for mobile... Do you have any thoughts/preference for the responsiveness of those links? I don't feel like that "toggle menu" is all that intuitive there. Would you prefer to have more of a hamburger style mobile menu for those links? Or maybe just breaking it down so that they are just visible in a single row underneath your bio at the top of the page on the mobile breakdown? I can certainly go with my instincts/inclination, but wanted to see if you had a preference first?

Yeah, I think I'd prefer the hamburger style dropdown.

One thing I'm realizing as I'm seeing it live is that it makes the masthead unnecessary. Can we remove that as well, so it looks like this:

image

>The about page is really very basic as you can see with just the filler text that you supplied. Do you need me to do any other markup/styling specifically for that page?

>Similarly, the projects page is also very basic with just the 2 links. Do you want me to work on any specific styling/markup for blurbs for that page?

These pages look fine to me as-is, but I'm open to suggestions on dressing them up. My only note is that the subscribe form seems to overwhelm those pages. Can we hide the email subscription form on the About and Projects pages?

Also, can we change "About Me" to just "About"? Seeing it live, the "Me" seems unnecessary now.

**Comment by shredtechular** [comment]
All those suggestions make complete sense to me @mtlynch !  This sounds like a plan to me!  Thanks for the input and I'll get to work on those changes!

**Comment by shredtechular** [comment]
@mtlynch 

I put in a new update to this PR now.  I updated the description, but specifically, the update addresses:

- [X] Enlarged the text size of the sidebar links to a more suitable size I think.
- [X] removed the masthead from larger screens, but as the sidebar breaks down responsively, it becomes visible displaying the sidebar nav links.
- [X] Updated the "About Me" text to simply "About"

Again, this is using the parent theme's mobile menu and it does use a "priority plus" [methodology](https://mmistakes.github.io/minimal-mistakes/docs/navigation/) to show as many navigation items that will fit horizontally with the hamburger menu containing the rest.  If you don't like the "priority plus" methodology we can remove that by customizing the theme further.  Additionally, if you don't like this hamburger menu style, we can do some more customization there too.

See what you think about this now and if you have any other changes/feedback you'd like to make to this.

**Comment by mtlynch** [comment]
This is great! I love it.

**Pull request merged**
